name: eternix-project
services:
  eternix-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: mbayoumieg/eternix-frontend:latest
    container_name: eternix-frontend-container
    ports:
      - '4200:80'
    networks:
      - eternix-network
networks:
  eternix-network:
    external: true
