server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # الـ / قبل index.html ضرورية جداً هنا
        try_files $uri $uri/ /index.html;
    }

    # منع الكاش للملفات الحساسة لضمان التحديث الفوري عند العميل
    location ~* \.(?:manifest|appcache|html?|xml|json)$ {
        root /usr/share/nginx/html;
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    # معالجة أخطاء السيرفر
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}